### ISSUE TITLE
geckoclient does crash on startup

### ISSUE THREAD

**Issue by sledge2019** [kalinrow/geckoclient#1]
First of all thanks for providing an MQTT-client for the in.touch from gecko - just what I am looking for.

Following the instructions from the github repository I installed geckolib (v0.4.7) and the async paho-mqtt implementation for python3.

After configuring config.py to match my environment, I started **client.py** directly for a testrun:

`root@jarvis:/opt/geckoclient# python3 client.py
Traceback (most recent call last):
  File "/opt/geckoclient/client.py", line 152, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/geckoclient/client.py", line 113, in main
    logger.info("Spa Version: " + spaman.facade.spa.version)
AttributeError: 'NoneType' object has no attribute 'spa'`

From my config.py-File:

`# SPA values
SPA_NAME = "Unser Traum"
SPA_IDENTIFIER = "SPAE8:EB:1B:1C:D0:72"`

UUID created from the website as recommended.

Any suggestions where I went wrong?

Thanks in advance.

**Comment by funky28** [comment]
Hi, first of all, A BIG second round of HUGE thanks for providing this client!.

I was having the same issue as described above, and I was able to fix it with a few tweaks to the client.py and config.py files. I will describe how the error manifested itself, and then I will provide my fix.

When I first installed the client, including the geckolib and asyncio_paho, everything was working perfectly from the start.. the Spa was automatically discovered and the parameters were passed to mosquitto... however, after a day or so I noticed that no parameters were being passed, and upon inspection, the gecko_client was throwing a fit (same exact error as above). 

In troubleshooting the issue, I tried to simply connect to my spa via the geckolib (via Python interpreter) and noticed my spa was not being found on the network.. which was super weird as it was just working a while ago, and the iOS app is able to see the spa.  Checking the log, the discovery is done by broadcasting a message over the network.. which I theorize that either my router or the OS firewall must have had a fit with it... then, I tried to connect to the SPA by specifying the IP address (my spa has a fix IP dictated by the router) as specified on the gecklib GitHub page. After this simply trick, I was able to connect once again to the spa.

Then, in order to tell the gecko client to use a specific IP, I had to add the following:
config.py >> Added a SPA_IP variable
```
# SPA values
SPA_NAME = "BullFrogSpa"
SPA_IDENTIFIER = "SPAxx:xx:xx:xx:xx:xx"
SPA_IP = "10.1.x.xxx"
```

client.py >> on line 92, added the IP variable to the call function:
`    async with MySpa(config.CLIENT_ID, spa_address=config.SPA_IP, spa_identifier=config.SPA_IDENTIFIER, spa_name=config.SPA_NAME) as spaman:`

Restarted the gecko client and....voila! everything was working again!

Hope this helps.

**Comment by sledge2019** [comment]
Thanks for providing that clue. In the meantime I tried something similar, just taking the relevant code-snippet from thew geckolib-example:

    async with SampleSpaMan(CLIENT_ID, spa_address=SPA_ADDRESS) as spaman:
        print("Looking for spas on your network ...")

        # Wait for descriptors to be available
        await spaman.wait_for_descriptors()

        if len(spaman.spa_descriptors) == 0:
            print("**** There were no spas found on your network.")
            return

        spa_descriptor = spaman.spa_descriptors[0]
        print(f"Connecting to {spa_descriptor.name} at {spa_descriptor.ipaddress} ...")
        await spaman.async_set_spa_info(
            spa_descriptor.ipaddress,
            spa_descriptor.identifier_as_string,
            spa_descriptor.name,
        )

Which also did the job for me after I put it into client.py following the line you mentioned.

One question on top: Am I the only one where the in.touch2 loses connection in my home network? Once every few days I have to either powercycle it or at least reset the network connection, else it is not accessible from the App (or via geckolib).

Just curious.

**Comment by funky28** [comment]
Glad to hear I was able to help!. Definitely there are more ways to skin the cat ;-)

In terms of the in.touch2 network, I'd personally say it is quite finicky... when I first got the Hot Tub, I set up the transmitter next to my router which is not as close the Tub... the app said the signal was good (about 60%) so I left it. 

Then the app will complain and push a notification saying that it lost connection with the tub (I'd say I would get one every two weeks)... trying to get rid of that, I moved the transmitter as close as physically possible to the tub (behind the same wall facing the patio) and the connectivity issues had gone down, but not disappeared. Every once in a while I do get a notification that it lost connectivity (this time, maybe every two months).

However, in both cases, this resolved itself in a matter of minutes (never longer than 30ish) and I have never had to power cycle either of the transmitters since I got them.

Hope this helps.

**Comment by sledge2019** [comment]
Finicky - nice word. Long forgotten for non-native-speakers. Anyway: For my setup it surely is LAN side of the transmitter.

Signal is about 90%, and I have prosumer network gear at home (unifi), still this things goes pitch black on the network after a non-determistic period of time - hours, sometimes days, but not much longer than that.
Support ticket created for that one - we will see.

Thanks again for your solution.

**Comment by kalinrow** [comment]
Dears,

also glad to see that the issue is solved already and that community is working so well.

The issue with [sledge2019](https://github.com/sledge2019) approach will be that you do not specify the tube, but simply use the first one identified. Fair enough, it will be very seldom that one have more than one tube... so it will work moist of the time ;) 

But strangely you have issue with the auto detection. As the old version had some memory issues I also restart the service each night and never saw an auto detection issues. Anyhow as the IP address is already part of the config.py file I will try to include this somehow in the client.py as well. So tubes with fixed IP can use that parameter additionally.

**Comment by kalinrow** [comment]
IP address option added with release 0.5.0.
That should fix the issue

**Comment by sledge2019** [comment]
1st: Thanks for taking this up.

Actually: Also "my" approach brings you to the desired pool, if you have a static IP assignemtnb (which I have in my router). And requires less info (just the IP and the UUID, that's about it, nothing else.

Will check during the holidays if the new version works for me - I thought I tried that approach but it did not work for me. But let me test, then I'll report.

**Comment by kalinrow** [comment]
Hi sledge,

I agree, your approach will work as well. I only fails if one has more than 1 SPA. Then always the first SPA will be contacted. 
It very unlikely having more than one SPA, but as I started with the approach to define the SPA and not to search for it, I kept it and added the IP address.

Looking forward to see the result of your test

**Comment by funky28** [comment]
Thanks for making the changes and incorporating the suggestion on version 0.5.0.

When I was debugging the issue about connectivity, it helped me when I had the geckolib save the log file so that gave me some ideas of what was going on. Per the git this is the command:

`>>> GeckoShell.run(["logfile client.log", "discover 192.168.1.2"])`

I wonder, if one could incorporate having the log file for the geckolib  just like we did for IP.. I guess I could play around with the config.py file and figure it out, but with the holidays approaching, tinkering time has decreased hehehe, so I figured I would ask.

Thanks!

**Comment by funky28** [comment]
Well, I think I answer the question myself LOL. Looking at the client.py file I see:

```
# prepare logger
def prepare_logger():
    global logger

    root = logging.getLogger()

    root.setLevel(config.DEBUG_LEVEL)

    # create routating file handler
    # log file location is depanding on write access
    try:
        rfh = logging.handlers.RotatingFileHandler(
            config.LOGFILE, mode='a', maxBytes=100000, backupCount=1, encoding=None, delay=False)
    except PermissionError:
        rfh = logging.handlers.RotatingFileHandler(
            "gecko_client.log", mode='a', maxBytes=100000, backupCount=1, encoding=None, delay=False)
    rfh.setLevel(config.DEBUG_LEVEL)

    # create formatter
    formatter = logging.Formatter(
        '%(asctime)s - %(name)s - %(levelname)s - %(message)s')

    # add formatter to rtf
    rfh.setFormatter(formatter)

    # separate level for geckolib
    geckolib = logging.getLogger("geckolib")
    geckolib.setLevel('WARN')

    # add rtf to logger
    root.addHandler(rfh)
```

So, does this means that the geckolib logs are then included on the geckoclient log? if so, I remember when I was troubleshooting that the geckoclient log had lots of information, but not everything that the geckolib was generating... could it be because the set level is default to WARN (as this is the default)? I must have been using INFO (default on the geckolib examples) and hence probably it had more info ....

**Comment by kalinrow** [comment]
Hi,
yes - you are right - gecklib logs are already part of the logging, but only WARN mode. The lib is quite talkative and really fills the log file quickly.
In the next version geckolib log level is also configurable from the config.py file
