### ISSUE TITLE
Setting watercare mode does not work

### ISSUE THREAD

**Issue by sledge2019** [kalinrow/geckoclient#6]
Hi,

a couple of days ago I updated to the latest (and greatest) version - especially the "refresh_all" is a nice function, if I want to ensure having an updated version of all values. Thanks for implementing

I wanted to use the "watercare" feature to start the circulation pump (+ heater), when I have surplus solar production, to reduce the amount of energy bought from the grid. 

At least for me it does not work.

Things I found ot:

The description mentions:

> To do so use the command topic %prefix%/watercare/cmnd with payload set_watercare=[MODE]

Whereas the definition in const.py

`TOPIC_WATERCARE = TOPIC+"/water_care"`

So I used the topic whirlpool/water_care/cmnd and send a message "set_watercare=2" to change the mode - here the excerpt from the logfile:

`2023-02-22 11:00:47,092 - mySpa - DEBUG - msg received: topic: whirlpool/water_care/cmnd, payload: set_watercare=2`

But nothing happens. Have not investigated further ;-)

**Comment by kalinrow** [comment]
Hello,
so far I did not use the water care setting via the service and sorry to be honest I did not even test it.Shame on me.
The issue was - beside the wrong documentation - a string/int mistake calling the underlying library. I have given the number as a string, whereas it should have been provided as in integer. It's fixed in 0.6.4.
Once we have our solar panels installed, I plan a similar control. Didn't thought about using the water care, only the heating, but indeed not a bad idea to also include the water care to avoid the circulation pump running to much during night. On the other it mus be assured that the cleaning is done. We have the  bromine generator, which needs to run a couple of hours per day...
